# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PYTHON\lexical_analysis\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1037, 725)
        self.lexicalanalys = QtWidgets.QTabWidget(Form)
        self.lexicalanalys.setGeometry(QtCore.QRect(0, 0, 1041, 771))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lexicalanalys.setFont(font)
        self.lexicalanalys.setMouseTracking(True)
        self.lexicalanalys.setObjectName("lexicalanalys")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1031, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.importFAtablepushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.importFAtablepushButton.setObjectName("importFAtablepushButton")
        self.horizontalLayout.addWidget(self.importFAtablepushButton)
        self.importtestfilepushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.importtestfilepushButton.setObjectName("importtestfilepushButton")
        self.horizontalLayout.addWidget(self.importtestfilepushButton)
        self.showlexicalrulespushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.showlexicalrulespushButton.setObjectName("showlexicalrulespushButton")
        self.horizontalLayout.addWidget(self.showlexicalrulespushButton)
        self.showDFAtablepushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.showDFAtablepushButton.setObjectName("showDFAtablepushButton")
        self.horizontalLayout.addWidget(self.showDFAtablepushButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 30, 1031, 371))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.testcontenttextEdit = QtWidgets.QTextEdit(self.layoutWidget1)
        self.testcontenttextEdit.setMouseTracking(False)
        self.testcontenttextEdit.setObjectName("testcontenttextEdit")
        self.verticalLayout.addWidget(self.testcontenttextEdit)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 400, 1041, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.begintestpushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.begintestpushButton.setObjectName("begintestpushButton")
        self.horizontalLayout_2.addWidget(self.begintestpushButton)
        self.savecontentpushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.savecontentpushButton.setObjectName("savecontentpushButton")
        self.horizontalLayout_2.addWidget(self.savecontentpushButton)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 430, 1031, 271))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget3)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.lexicalanalys.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lexicalanalys.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lexicalanalys.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.lexicalanalys.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.importFAtablepushButton.setText(_translate("Form", "导入FA表"))
        self.importtestfilepushButton.setText(_translate("Form", "导入测试文件"))
        self.showlexicalrulespushButton.setText(_translate("Form", "查看词法规则"))
        self.showDFAtablepushButton.setText(_translate("Form", "查看DFA转换表"))
        self.label.setText(_translate("Form", "测试内容："))
        self.begintestpushButton.setText(_translate("Form", "开始测试"))
        self.savecontentpushButton.setText(_translate("Form", "保存内容"))
        self.label_2.setText(_translate("Form", "测试结果："))
        self.lexicalanalys.setTabText(self.lexicalanalys.indexOf(self.tab), _translate("Form", "词法分析"))
        self.lexicalanalys.setTabText(self.lexicalanalys.indexOf(self.tab_2), _translate("Form", "语法分析"))
        self.lexicalanalys.setTabText(self.lexicalanalys.indexOf(self.tab_3), _translate("Form", "语义分析"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
