# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PYTHON\lab1\UI\MainWindowtest.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1564, 890)
        self.lexicalanalys = QtWidgets.QTabWidget(Form)
        self.lexicalanalys.setGeometry(QtCore.QRect(0, 0, 1561, 891))
        font = QtGui.QFont()
        font.setItalic(False)
        self.lexicalanalys.setFont(font)
        self.lexicalanalys.setMouseTracking(True)
        self.lexicalanalys.setObjectName("lexicalanalys")
        self.tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1551, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.importFAtablepushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.importFAtablepushButton.setObjectName("importFAtablepushButton")
        self.horizontalLayout.addWidget(self.importFAtablepushButton)
        self.importtestfilepushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.importtestfilepushButton.setObjectName("importtestfilepushButton")
        self.horizontalLayout.addWidget(self.importtestfilepushButton)
        self.showlexicalrulespushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.showlexicalrulespushButton.setObjectName("showlexicalrulespushButton")
        self.horizontalLayout.addWidget(self.showlexicalrulespushButton)
        self.showDFAtablepushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.showDFAtablepushButton.setObjectName("showDFAtablepushButton")
        self.horizontalLayout.addWidget(self.showDFAtablepushButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 30, 1551, 361))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 400, 1551, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.begintestpushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.begintestpushButton.setObjectName("begintestpushButton")
        self.horizontalLayout_2.addWidget(self.begintestpushButton)
        self.savecontentpushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.savecontentpushButton.setObjectName("savecontentpushButton")
        self.horizontalLayout_2.addWidget(self.savecontentpushButton)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(1, 432, 1551, 431))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget3)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.textBrowser)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.layoutWidget3)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.horizontalLayout_3.addWidget(self.textBrowser_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.lexicalanalys.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lexicalanalys.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lexicalanalys.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.lexicalanalys.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.importFAtablepushButton.setText(_translate("Form", "导入FA表"))
        self.importtestfilepushButton.setText(_translate("Form", "导入测试文件"))
        self.showlexicalrulespushButton.setText(_translate("Form", "查看词法规则"))
        self.showDFAtablepushButton.setText(_translate("Form", "查看DFA转换表"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">测试内容：</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "源程序"))
        self.begintestpushButton.setText(_translate("Form", "开始测试"))
        self.savecontentpushButton.setText(_translate("Form", "保存内容"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">测试结果：</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">错误报告：</span></p></body></html>"))
        self.lexicalanalys.setTabText(self.lexicalanalys.indexOf(self.tab), _translate("Form", "词法分析"))
        self.lexicalanalys.setTabText(self.lexicalanalys.indexOf(self.tab_2), _translate("Form", "语法分析"))
        self.lexicalanalys.setTabText(self.lexicalanalys.indexOf(self.tab_3), _translate("Form", "语义分析"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
